# Generated by Django 5.1.2 on 2024-11-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domashka_app', '0001_domashka_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='domashka',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
